 pipeline {
    agent any  // Runs on any available Jenkins agent

  environment {
        JAVA_HOME = tool name: 'JDK17', type: 'jdk'  // Ensure JDK 17 is installed in Jenkins
        PATH = "${JAVA_HOME}/bin:${env.PATH}"
    }

 stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/Jayaprakashh/spring-boot-app-demo-Jekin.git'
            }
        }

 stage('Setup Maven') {
            steps {
                script {
                    def mvnHome = tool name: 'Maven', type: 'maven'
                    env.PATH = "${mvnHome}/bin:${env.PATH}"
                }
            }
        }
     
        stage('Build Application') {
            steps {
                sh 'mvn clean package -DskipTests'

            }
        }
       

        stage('Run Application') {
            steps {
                bat 'java -jar target/*.jar'  // Runs the built Spring Boot JAR file
            }
        }
    }

     post {
        success {
            echo 'Build completed successfully!'
        }
        failure {
            echo 'Build failed! Check the logs for details.'
        }
    }
}

